from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Dict, Iterable, Optional, Tuple


@dataclass(frozen=True)
class BatchStep:
    step_id: str
    kind: str
    description: str
    params_file: str = ""
    script_path: Optional[str] = None
    python_bin_override: Optional[str] = None
    mode: Optional[str] = None
    baseline_name: Optional[str] = None
    feature_mode: Optional[str] = None
    sbi_method: Optional[str] = None
    density_estimator: Optional[str] = None
    pass_curr: bool = False
    pass_data_dir: bool = False
    save_predictions: Optional[str] = None
    load_from_step: Optional[str] = None
    split_eval_after_train: bool = False
    skip_inline_split_eval: bool = False
    n_train: Optional[int] = None
    eval_limit: Optional[int] = None
    posterior_samples: Optional[int] = None
    stop_after_epochs: Optional[int] = None
    max_num_epochs: Optional[int] = None
    seed: Optional[int] = None
    nproc_per_node: Optional[int] = None
    step_nnodes: Optional[int] = None
    extra_args: Tuple[str, ...] = ()
    env_overrides: Tuple[Tuple[str, str], ...] = ()


@dataclass(frozen=True)
class BatchDefinition:
    batch_id: str
    sequence: int
    title: str
    suite: str
    scientific_role: str
    summary: str
    requires_hh_tar: bool = False
    requires_slurm: bool = False
    cluster_label: Optional[str] = None
    min_nodes: int = 0
    preferred_gpu: Optional[str] = None
    depends_on: Tuple[str, ...] = ()
    notes: Tuple[str, ...] = ()
    steps: Tuple[BatchStep, ...] = ()


BATCHES: Tuple[BatchDefinition, ...] = (
    BatchDefinition(
        batch_id="smk01_fhn_baseline",
        sequence=10,
        title="FitzHugh-Nagumo baseline smoke",
        suite="falcon_a30_smoke",
        scientific_role="supporting",
        summary="Runs the shipped FHN smoke train and eval path, so the public code surface can be validated before any HH workload is attempted.",
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=4,
        preferred_gpu="A30",
        steps=(
            BatchStep(
                step_id="train",
                kind="dnn",
                description="FHN smoke training run",
                params_file="src/pytorch/configs/params_dnn_tar_smoke.yaml",
                mode="train",
                save_predictions="none",
            ),
            BatchStep(
                step_id="eval",
                kind="dnn",
                description="FHN smoke evaluation run against the latest checkpoint from the preceding train step",
                params_file="src/pytorch/configs/params_dnn_tar_smoke.yaml",
                mode="eval",
                load_from_step="train",
                save_predictions="none",
            ),
        ),
    ),
    BatchDefinition(
        batch_id="smk02_hh_dnn",
        sequence=20,
        title="Hodgkin-Huxley DNN smoke",
        suite="falcon_a30_smoke",
        scientific_role="primary_support",
        summary="Exercises the HH DNN train and eval path from a fresh checkout, using only the external HH tarball and the automatic `.prepared_data` extraction flow.",
        requires_hh_tar=True,
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=4,
        preferred_gpu="A30",
        notes=(
            "This batch validates the public HH DNN path, rather than the full canonical campaign scale.",
        ),
        steps=(
            BatchStep(
                step_id="train",
                kind="dnn",
                description="HH smoke training run",
                params_file="src/pytorch/configs/hh/params_dnn_tar_hh_smoke.yaml",
                mode="train",
                pass_curr=True,
                save_predictions="none",
            ),
            BatchStep(
                step_id="eval",
                kind="dnn",
                description="HH smoke evaluation run against the latest checkpoint from the preceding train step",
                params_file="src/pytorch/configs/hh/params_dnn_tar_hh_smoke.yaml",
                mode="eval",
                pass_curr=True,
                load_from_step="train",
                save_predictions="none",
            ),
        ),
    ),
    BatchDefinition(
        batch_id="smk03_hh_classical",
        sequence=30,
        title="Hodgkin-Huxley classical smoke",
        suite="falcon_a30_smoke",
        scientific_role="primary_support",
        summary="Runs the public classical HH baseline driver on the smoke contract, so the non-neural public path can be validated independently of DNN training.",
        requires_hh_tar=True,
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=4,
        preferred_gpu="A30",
        steps=(
            BatchStep(
                step_id="extra_trees_200_raw",
                kind="classical",
                description="Extra Trees smoke reference on raw trace features",
                params_file="src/pytorch/configs/hh/params_dnn_tar_hh_smoke.yaml",
                baseline_name="extra_trees_200",
                feature_mode="raw",
                pass_curr=True,
            ),
        ),
    ),
    BatchDefinition(
        batch_id="smk04_hh_sbi",
        sequence=40,
        title="Hodgkin-Huxley SBI smoke",
        suite="falcon_a30_smoke",
        scientific_role="boundary_support",
        summary="Runs the public HH SBI driver on a compact SNPE smoke contract, so the posterior-oriented public path can be validated independently of the main DNN and classical paths.",
        requires_hh_tar=True,
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=4,
        preferred_gpu="A30",
        steps=(
            BatchStep(
                step_id="snpe_maf_raw",
                kind="sbi",
                description="SNPE-MAF smoke reference on raw trace features",
                params_file="src/pytorch/configs/hh/params_dnn_tar_hh_smoke.yaml",
                sbi_method="snpe",
                density_estimator="maf",
                feature_mode="raw",
                pass_curr=True,
                n_train=64,
                eval_limit=64,
                posterior_samples=8,
                stop_after_epochs=1,
                max_num_epochs=1,
                seed=123,
            ),
        ),
    ),
    BatchDefinition(
        batch_id="smk05_bayesflow_frameworks",
        sequence=45,
        title="BayesFlow framework smoke",
        suite="canonical_complete_smoke",
        scientific_role="coverage_expansion",
        summary="Runs reduced BayesFlow framework branches, so the newly added aligned-framework codepaths can be validated cheaply before the full canonical suite is attempted.",
        requires_hh_tar=True,
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=4,
        preferred_gpu="A30",
        depends_on=("smk04_hh_sbi",),
        steps=(
            BatchStep(
                step_id="bayesflow_concat",
                kind="script",
                description="BayesFlow concat smoke",
                script_path="scripts/run_hh_track4_aligned_multicurrent_bayesflow_20260425.py",
                python_bin_override=".venv-bayesflow/bin/python",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                extra_args=(
                    "--aggregation", "concat",
                    "--feature-mode", "raw_plus_fft256_summary12",
                    "--n-train", "128",
                    "--n-validate", "64",
                    "--n-test", "32",
                    "--epochs", "1",
                    "--batch-size", "16",
                    "--posterior-samples", "8",
                    "--sample-batch-size", "8",
                    "--diagnostic-samples", "8",
                    "--seed", "20260429",
                ),
            ),
            BatchStep(
                step_id="bayesflow_meanstd",
                kind="script",
                description="BayesFlow meanstd smoke",
                script_path="scripts/run_hh_track4_aligned_multicurrent_bayesflow_20260425.py",
                python_bin_override=".venv-bayesflow/bin/python",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                extra_args=(
                    "--aggregation", "meanstd",
                    "--feature-mode", "raw_plus_fft256_summary12",
                    "--n-train", "128",
                    "--n-validate", "64",
                    "--n-test", "32",
                    "--epochs", "1",
                    "--batch-size", "16",
                    "--posterior-samples", "8",
                    "--sample-batch-size", "8",
                    "--diagnostic-samples", "8",
                    "--seed", "20260429",
                ),
            ),
            BatchStep(
                step_id="bayesflow_structured",
                kind="script",
                description="BayesFlow structured smoke",
                script_path="scripts/run_hh_track4_aligned_multicurrent_bayesflow_structured_20260425.py",
                python_bin_override=".venv-bayesflow/bin/python",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                extra_args=(
                    "--feature-mode", "raw_plus_fft256_summary12",
                    "--n-train", "128",
                    "--n-validate", "64",
                    "--n-test", "32",
                    "--epochs", "1",
                    "--batch-size", "16",
                    "--posterior-samples", "8",
                    "--sample-batch-size", "8",
                    "--diagnostic-samples", "8",
                    "--seed", "20260429",
                ),
            ),
            BatchStep(
                step_id="bayesflow_set",
                kind="script",
                description="BayesFlow set-posterior smoke",
                script_path="scripts/run_hh_track4_aligned_multicurrent_bayesflow_set_20260426.py",
                python_bin_override=".venv-bayesflow/bin/python",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                extra_args=(
                    "--feature-mode", "raw_plus_fft256_summary12",
                    "--summary-network", "set_transformer",
                    "--n-train", "128",
                    "--n-validate", "64",
                    "--n-test", "32",
                    "--epochs", "1",
                    "--batch-size", "16",
                    "--posterior-samples", "8",
                    "--sample-batch-size", "8",
                    "--diagnostic-samples", "8",
                    "--seed", "20260429",
                ),
            ),
            BatchStep(
                step_id="bayesflow_temporal",
                kind="script",
                description="BayesFlow temporal smoke",
                script_path="scripts/run_hh_track4_aligned_multicurrent_bayesflow_temporal_20260426.py",
                python_bin_override=".venv-bayesflow/bin/python",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                extra_args=(
                    "--summary-network", "time_series_transformer",
                    "--time-points", "256",
                    "--n-train", "64",
                    "--n-validate", "32",
                    "--n-test", "16",
                    "--epochs", "1",
                    "--batch-size", "8",
                    "--posterior-samples", "8",
                    "--sample-batch-size", "4",
                    "--diagnostic-samples", "8",
                    "--seed", "20260429",
                ),
            ),
        ),
    ),
    BatchDefinition(
        batch_id="smk06_swyft_frameworks",
        sequence=46,
        title="Swyft framework smoke",
        suite="canonical_complete_smoke",
        scientific_role="coverage_expansion",
        summary="Runs reduced Swyft framework branches, so the newly added native and TMNRE-style Swyft codepaths can be validated cheaply before the full canonical suite is attempted.",
        requires_hh_tar=True,
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=4,
        preferred_gpu="A30",
        depends_on=("smk04_hh_sbi",),
        steps=(
            BatchStep(
                step_id="swyft_concat",
                kind="script",
                description="Swyft concat smoke",
                script_path="scripts/run_hh_track4_aligned_multicurrent_swyft_20260425.py",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                extra_args=(
                    "--aggregation", "concat",
                    "--n-train", "128",
                    "--n-validate", "64",
                    "--n-test", "32",
                    "--max-epochs", "1",
                    "--batch-size", "16",
                    "--inference-batch-size", "16",
                    "--num-workers", "0",
                    "--device", "gpu",
                    "--seed", "20260429",
                ),
            ),
            BatchStep(
                step_id="swyft_meanstd",
                kind="script",
                description="Swyft meanstd smoke",
                script_path="scripts/run_hh_track4_aligned_multicurrent_swyft_20260425.py",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                extra_args=(
                    "--aggregation", "meanstd",
                    "--n-train", "128",
                    "--n-validate", "64",
                    "--n-test", "32",
                    "--max-epochs", "1",
                    "--batch-size", "16",
                    "--inference-batch-size", "16",
                    "--num-workers", "0",
                    "--device", "gpu",
                    "--seed", "20260429",
                ),
            ),
            BatchStep(
                step_id="swyft_structured",
                kind="script",
                description="Swyft structured smoke",
                script_path="scripts/run_hh_track4_aligned_multicurrent_swyft_structured_20260425.py",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                extra_args=(
                    "--n-train", "128",
                    "--n-validate", "64",
                    "--n-test", "32",
                    "--max-epochs", "1",
                    "--batch-size", "16",
                    "--inference-batch-size", "16",
                    "--num-workers", "0",
                    "--device", "gpu",
                    "--seed", "20260429",
                ),
            ),
            BatchStep(
                step_id="swyft_tmnre",
                kind="script",
                description="Swyft TMNRE smoke",
                script_path="scripts/run_hh_track4_aligned_multicurrent_swyft_tmnre_20260425.py",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                load_from_step="swyft_meanstd",
                extra_args=(
                    "--stage1-run-dir", "{LOAD_FROM_STEP_ROOT}",
                    "--n-train", "128",
                    "--n-validate", "64",
                    "--n-test", "32",
                    "--max-epochs", "1",
                    "--batch-size", "16",
                    "--inference-batch-size", "16",
                    "--num-workers", "0",
                    "--bound-observations", "16",
                    "--bound-quantiles", "0.25:0.75",
                    "--device", "gpu",
                    "--seed", "20260429",
                ),
            ),
            BatchStep(
                step_id="swyft_tmnre_score_prune",
                kind="script",
                description="Swyft TMNRE score-prune smoke",
                script_path="scripts/run_hh_track4_aligned_multicurrent_swyft_tmnre_score_prune_20260426.py",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                load_from_step="swyft_meanstd",
                extra_args=(
                    "--stage1-run-dir", "{LOAD_FROM_STEP_ROOT}",
                    "--n-train", "128",
                    "--n-validate", "64",
                    "--n-test", "32",
                    "--max-epochs", "1",
                    "--batch-size", "16",
                    "--inference-batch-size", "16",
                    "--num-workers", "0",
                    "--score-observations", "16",
                    "--keep-fracs", "0.5",
                    "--device", "gpu",
                    "--seed", "20260429",
                ),
            ),
        ),
    ),
    BatchDefinition(
        batch_id="smk07_posterior_decision_rules",
        sequence=47,
        title="Posterior decision-rule smoke",
        suite="canonical_complete_smoke",
        scientific_role="coverage_expansion",
        summary="Runs a reduced posterior decision-rule analysis across the newly added BayesFlow and Swyft smoke outputs, together with the existing public SBI smoke output.",
        requires_hh_tar=True,
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=4,
        preferred_gpu="A30",
        depends_on=("smk05_bayesflow_frameworks", "smk06_swyft_frameworks"),
        steps=(
            BatchStep(
                step_id="decision_rule_analysis",
                kind="script",
                description="Posterior decision-rule smoke analysis",
                script_path="scripts/analyze_hh_track4_posterior_decision_rules_20260425.py",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                extra_args=(
                    "--run-roots",
                    "{RUN_ROOT}/smk04_hh_sbi,{RUN_ROOT}/smk05_bayesflow_frameworks,{RUN_ROOT}/smk06_swyft_frameworks",
                    "--n-train", "128",
                    "--n-validate", "64",
                    "--n-test", "32",
                ),
            ),
        ),
    ),
    BatchDefinition(
        batch_id="smk08_assumption_conditioned_surrogates",
        sequence=48,
        title="Assumption-conditioned surrogate smoke",
        suite="canonical_complete_smoke",
        scientific_role="coverage_expansion",
        summary="Runs reduced compact-HH surrogate branches, so the newly added active-design, Wasserstein, hybrid-refinement, and ASNPE paths can be validated before the full canonical suite is attempted.",
        requires_hh_tar=True,
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=4,
        preferred_gpu="A30",
        steps=(
            BatchStep(
                step_id="compact_hh_sandbox",
                kind="script",
                description="Compact-HH sandbox smoke",
                script_path="scripts/run_hh_track4_assumption_conditioned_compact_hh_sandbox_20260424.py",
                pass_data_dir=True,
                extra_args=(
                    "--n-observed", "16",
                    "--n-param-samples", "8",
                    "--trace-length", "1000",
                    "--current-gains", "20,40",
                    "--workers", "1",
                    "--seed", "20260429",
                ),
            ),
            BatchStep(
                step_id="compact_hh_fit_search",
                kind="script",
                description="Compact-HH fit-search smoke",
                script_path="scripts/run_hh_track4_assumption_conditioned_compact_hh_fit_search_20260424.py",
                pass_data_dir=True,
                extra_args=(
                    "--n-exemplars", "1",
                    "--trace-length", "1000",
                    "--maxiter", "2",
                    "--popsize", "2",
                    "--workers", "1",
                    "--seed", "20260429",
                ),
            ),
            BatchStep(
                step_id="hybrid_refinement",
                kind="script",
                description="Hybrid refinement smoke",
                script_path="scripts/run_hh_track4_assumption_conditioned_hybrid_refinement_20260425.py",
                pass_data_dir=True,
                extra_args=(
                    "--init-mode", "midpoint",
                    "--n-exemplars", "1",
                    "--trace-length", "1000",
                    "--maxiter", "10",
                    "--seed", "20260429",
                ),
            ),
            BatchStep(
                step_id="wasserstein_abc",
                kind="script",
                description="Wasserstein ABC smoke",
                script_path="scripts/run_hh_track4_assumption_conditioned_wasserstein_abc_20260425.py",
                pass_data_dir=True,
                extra_args=(
                    "--n-exemplars", "1",
                    "--trace-length", "1000",
                    "--n-particles", "16",
                    "--keep-top", "4",
                    "--n-projections", "8",
                    "--seed", "20260429",
                ),
            ),
            BatchStep(
                step_id="active_sequential_policy_suite",
                kind="script",
                description="Active-sequential policy-suite smoke",
                script_path="scripts/run_hh_track4_assumption_conditioned_active_sequential_policy_suite_20260425.py",
                extra_args=(
                    "--n-episodes", "1",
                    "--n-particles", "16",
                    "--n-rounds", "2",
                ),
            ),
            BatchStep(
                step_id="asnpe_surrogate",
                kind="script",
                description="ASNPE surrogate smoke",
                script_path="scripts/run_hh_track4_assumption_conditioned_asnpe_20260426.py",
                extra_args=(
                    "--ensemble-size", "1",
                    "--n-rounds", "2",
                    "--initial-sims", "32",
                    "--round-sims", "8",
                    "--candidate-pool", "32",
                    "--epochs", "2",
                    "--posterior-samples", "32",
                    "--sample-batch-size", "16",
                    "--workers", "1",
                    "--trace-length", "1000",
                    "--seed", "20260429",
                ),
            ),
        ),
    ),
    BatchDefinition(
        batch_id="fal01_hh_4node_a30_dnn",
        sequence=50,
        title="Falcon 4-node A30 HH DNN canonical run",
        suite="canonical_falcon",
        scientific_role="primary",
        summary="Runs the current public distributed HH DNN entrypoint inside a Falcon Slurm allocation, using the canonical 4-node A30 placeholder topology and a separate train and eval step.",
        requires_hh_tar=True,
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=4,
        preferred_gpu="A30",
        notes=(
            "This batch is environment-anchored. It is intended for cluster reproduction, rather than standalone workstation execution.",
        ),
        steps=(
            BatchStep(
                step_id="train",
                kind="interactive_dnn",
                description="Distributed HH DNN train step inside a 4-node Falcon allocation",
                params_file="src/pytorch/configs/hh/params_dnn_tar_hh.yaml",
                pass_curr=True,
                save_predictions="none",
                split_eval_after_train=True,
                skip_inline_split_eval=True,
                step_nnodes=4,
                nproc_per_node=2,
            ),
            BatchStep(
                step_id="eval",
                kind="interactive_dnn",
                description="Post-train evaluation step against the latest checkpoint from the preceding distributed HH DNN train step",
                params_file="src/pytorch/configs/hh/params_dnn_tar_hh.yaml",
                pass_curr=True,
                save_predictions="none",
                load_from_step="train",
                step_nnodes=4,
                nproc_per_node=2,
            ),
        ),
    ),
    BatchDefinition(
        batch_id="fal02_hh_classical_reference",
        sequence=60,
        title="Falcon HH classical reference",
        suite="canonical_falcon",
        scientific_role="primary_support",
        summary="Runs the public classical HH baseline driver under the documented Falcon environment, so the classical public reference can be regenerated within the same cluster contract.",
        requires_hh_tar=True,
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=1,
        preferred_gpu="A30",
        steps=(
            BatchStep(
                step_id="extra_trees_200_raw",
                kind="classical",
                description="Cluster-side Extra Trees reference on raw trace features",
                params_file="src/pytorch/configs/hh/params_classical_hh_campaign.yaml",
                baseline_name="extra_trees_200",
                feature_mode="raw",
                pass_curr=True,
            ),
        ),
    ),
    BatchDefinition(
        batch_id="fal03_hh_sbi_reference",
        sequence=70,
        title="Falcon HH SBI reference",
        suite="canonical_falcon",
        scientific_role="boundary_support",
        summary="Runs the public HH SBI driver inside the documented Falcon environment, so the posterior-oriented public reference can be regenerated within the same cluster contract.",
        requires_hh_tar=True,
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=1,
        preferred_gpu="A30",
        steps=(
            BatchStep(
                step_id="snpe_maf_raw",
                kind="sbi",
                description="Cluster-side SNPE-MAF reference on raw trace features",
                params_file="src/pytorch/configs/hh/params_sbi_hh_campaign.yaml",
                sbi_method="snpe",
                density_estimator="maf",
                feature_mode="raw",
                pass_curr=True,
                n_train=12288,
                eval_limit=1024,
                posterior_samples=16,
                stop_after_epochs=20,
                max_num_epochs=100,
                seed=1201,
            ),
        ),
    ),
    BatchDefinition(
        batch_id="sci01_benchmark_parity",
        sequence=110,
        title="Scientific smoke: benchmark parity",
        suite="scientific_smoke",
        scientific_role="supporting",
        summary="Falcon-sized FHN benchmark reproduction that validates the baseline train and eval path used to anchor the benchmark-parity thread.",
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=4,
        preferred_gpu="A30",
        steps=(
            BatchStep(
                step_id="train",
                kind="dnn",
                description="FHN parity-smoke training run",
                params_file="src/pytorch/configs/params_dnn_tar.yaml",
                mode="train",
                save_predictions="none",
            ),
            BatchStep(
                step_id="eval",
                kind="dnn",
                description="FHN parity-smoke evaluation run",
                params_file="src/pytorch/configs/params_dnn_tar.yaml",
                mode="eval",
                load_from_step="train",
                save_predictions="none",
            ),
        ),
    ),
    BatchDefinition(
        batch_id="sci02_execution_policy",
        sequence=120,
        title="Scientific smoke: execution configuration and run policy",
        suite="scientific_smoke",
        scientific_role="supporting",
        summary="Falcon-sized HH distributed reproduction across 1-node, 2-node, and 4-node layouts, so the execution-policy thread can be exercised through the same distributed public entrypoint.",
        requires_hh_tar=True,
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=4,
        preferred_gpu="A30",
        depends_on=("sci01_benchmark_parity",),
        steps=(
            BatchStep(
                step_id="one_node_train",
                kind="interactive_dnn",
                description="Single-node HH distributed smoke train",
                params_file="src/pytorch/configs/hh/params_dnn_tar_hh.yaml",
                pass_curr=True,
                save_predictions="none",
                split_eval_after_train=True,
                skip_inline_split_eval=True,
                step_nnodes=1,
                nproc_per_node=1,
                env_overrides=(("DATA_ACCESS_MODE", "tar_in_place"),),
            ),
            BatchStep(
                step_id="one_node_eval",
                kind="interactive_dnn",
                description="Single-node HH distributed smoke eval",
                params_file="src/pytorch/configs/hh/params_dnn_tar_hh.yaml",
                pass_curr=True,
                save_predictions="none",
                load_from_step="one_node_train",
                step_nnodes=1,
                nproc_per_node=1,
                env_overrides=(("DATA_ACCESS_MODE", "tar_in_place"),),
            ),
            BatchStep(
                step_id="two_node_train",
                kind="interactive_dnn",
                description="Two-node HH distributed smoke train",
                params_file="src/pytorch/configs/hh/params_dnn_tar_hh.yaml",
                pass_curr=True,
                save_predictions="none",
                split_eval_after_train=True,
                skip_inline_split_eval=True,
                step_nnodes=2,
                nproc_per_node=1,
                env_overrides=(("DATA_ACCESS_MODE", "tar_in_place"),),
            ),
            BatchStep(
                step_id="two_node_eval",
                kind="interactive_dnn",
                description="Two-node HH distributed smoke eval",
                params_file="src/pytorch/configs/hh/params_dnn_tar_hh.yaml",
                pass_curr=True,
                save_predictions="none",
                load_from_step="two_node_train",
                step_nnodes=2,
                nproc_per_node=1,
                env_overrides=(("DATA_ACCESS_MODE", "tar_in_place"),),
            ),
            BatchStep(
                step_id="four_node_train",
                kind="interactive_dnn",
                description="Four-node HH distributed smoke train",
                params_file="src/pytorch/configs/hh/params_dnn_tar_hh.yaml",
                pass_curr=True,
                save_predictions="none",
                split_eval_after_train=True,
                skip_inline_split_eval=True,
                step_nnodes=4,
                nproc_per_node=2,
                env_overrides=(("DATA_ACCESS_MODE", "tar_in_place"),),
            ),
            BatchStep(
                step_id="four_node_eval",
                kind="interactive_dnn",
                description="Four-node HH distributed smoke eval",
                params_file="src/pytorch/configs/hh/params_dnn_tar_hh.yaml",
                pass_curr=True,
                save_predictions="none",
                load_from_step="four_node_train",
                step_nnodes=4,
                nproc_per_node=2,
                env_overrides=(("DATA_ACCESS_MODE", "tar_in_place"),),
            ),
        ),
    ),
    BatchDefinition(
        batch_id="sci03_direct_frontier",
        sequence=130,
        title="Scientific smoke: direct fixed-task frontier",
        suite="scientific_smoke",
        scientific_role="primary",
        summary="Falcon-sized HH direct-comparison reproduction across the public neural and classical representatives, so the direct frontier can be regenerated under the larger campaign contracts.",
        requires_hh_tar=True,
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=4,
        preferred_gpu="A30",
        depends_on=("sci02_execution_policy",),
        steps=(
            BatchStep(
                step_id="dnn_train",
                kind="dnn",
                description="Neural direct smoke train",
                params_file="src/pytorch/configs/hh/params_dnn_tar_hh.yaml",
                mode="train",
                pass_curr=True,
                save_predictions="none",
            ),
            BatchStep(
                step_id="dnn_eval",
                kind="dnn",
                description="Neural direct smoke eval",
                params_file="src/pytorch/configs/hh/params_dnn_tar_hh.yaml",
                mode="eval",
                pass_curr=True,
                load_from_step="dnn_train",
                save_predictions="none",
            ),
            BatchStep(
                step_id="extra_trees_clean",
                kind="classical",
                description="Extra Trees direct clean smoke reference",
                params_file="src/pytorch/configs/hh/params_classical_hh_campaign.yaml",
                baseline_name="extra_trees_500_depth20",
                feature_mode="raw",
                pass_curr=True,
            ),
            BatchStep(
                step_id="knn_clean",
                kind="classical",
                description="kNN direct clean smoke reference",
                params_file="src/pytorch/configs/hh/params_classical_hh_campaign.yaml",
                baseline_name="knn_k11",
                feature_mode="raw",
                pass_curr=True,
            ),
        ),
    ),
    BatchDefinition(
        batch_id="sci04_posterior_followup",
        sequence=140,
        title="Scientific smoke: posterior and representation follow-up",
        suite="scientific_smoke",
        scientific_role="boundary",
        summary="Falcon-sized HH posterior reproduction across representation and family choices, so the representation-enrichment and posterior-family thread can be exercised publicly.",
        requires_hh_tar=True,
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=4,
        preferred_gpu="A30",
        depends_on=("sci03_direct_frontier",),
        steps=(
            BatchStep(
                step_id="snpe_raw",
                kind="sbi",
                description="SNPE-MAF raw-trace smoke reference",
                params_file="src/pytorch/configs/hh/params_sbi_hh_campaign.yaml",
                sbi_method="snpe",
                density_estimator="maf",
                feature_mode="raw",
                pass_curr=True,
                n_train=12288,
                eval_limit=1024,
                posterior_samples=16,
                stop_after_epochs=20,
                max_num_epochs=100,
                seed=1201,
                extra_args=("--hidden-features", "192", "--num-transforms", "8"),
            ),
            BatchStep(
                step_id="snpe_raw_fft_summary",
                kind="sbi",
                description="SNPE-MAF smoke with enriched raw-plus-FFT-plus-summary features",
                params_file="src/pytorch/configs/hh/params_sbi_hh_campaign.yaml",
                sbi_method="snpe",
                density_estimator="maf",
                feature_mode="raw_plus_fft256_summary12",
                pass_curr=True,
                n_train=12288,
                eval_limit=1024,
                posterior_samples=16,
                stop_after_epochs=20,
                max_num_epochs=100,
                seed=1201,
                extra_args=("--hidden-features", "192", "--num-transforms", "8"),
            ),
            BatchStep(
                step_id="fmpe_raw_fft_summary",
                kind="sbi",
                description="FMPE smoke with enriched raw-plus-FFT-plus-summary features",
                params_file="src/pytorch/configs/hh/params_sbi_hh_campaign.yaml",
                sbi_method="fmpe",
                density_estimator="maf",
                feature_mode="raw_plus_fft256_summary12",
                pass_curr=True,
                n_train=12288,
                eval_limit=1024,
                posterior_samples=16,
                stop_after_epochs=20,
                max_num_epochs=100,
                seed=1201,
                extra_args=("--hidden-features", "192", "--num-transforms", "8"),
            ),
            BatchStep(
                step_id="snpe_median_rule",
                kind="sbi",
                description="SNPE-MAF smoke with a posterior-median decision rule",
                params_file="src/pytorch/configs/hh/params_sbi_hh_campaign.yaml",
                sbi_method="snpe",
                density_estimator="maf",
                feature_mode="raw_plus_fft256_summary12",
                pass_curr=True,
                n_train=12288,
                eval_limit=1024,
                posterior_samples=16,
                stop_after_epochs=20,
                max_num_epochs=100,
                seed=1201,
                extra_args=("--decision-rule", "median", "--hidden-features", "192", "--num-transforms", "8"),
            ),
        ),
    ),
    BatchDefinition(
        batch_id="sci05_robustness",
        sequence=150,
        title="Scientific smoke: robustness and perturbation response",
        suite="scientific_smoke",
        scientific_role="boundary",
        summary="Falcon-sized HH robustness reproduction that exercises the public direct and posterior pathways under additive noise, drift, and masking.",
        requires_hh_tar=True,
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=4,
        preferred_gpu="A30",
        depends_on=("sci04_posterior_followup",),
        steps=(
            BatchStep(
                step_id="extra_trees_noise020",
                kind="classical",
                description="Extra Trees smoke under additive noise 0.20",
                params_file="src/pytorch/configs/hh/params_classical_hh_campaign.yaml",
                baseline_name="extra_trees_500_depth20",
                feature_mode="raw",
                pass_curr=True,
                extra_args=(
                    "--features-additive-noise-std",
                    "0.20",
                    "--random-seed",
                    "123",
                ),
            ),
            BatchStep(
                step_id="knn_noise020",
                kind="classical",
                description="kNN smoke under additive noise 0.20",
                params_file="src/pytorch/configs/hh/params_classical_hh_campaign.yaml",
                baseline_name="knn_k11",
                feature_mode="raw",
                pass_curr=True,
                extra_args=(
                    "--features-additive-noise-std",
                    "0.20",
                    "--random-seed",
                    "123",
                ),
            ),
            BatchStep(
                step_id="snpe_drift010",
                kind="sbi",
                description="SNPE-MAF smoke with matched drift retraining and drift evaluation",
                params_file="src/pytorch/configs/hh/params_sbi_hh_campaign.yaml",
                sbi_method="snpe",
                density_estimator="maf",
                feature_mode="raw_plus_fft256_summary12",
                pass_curr=True,
                n_train=12288,
                eval_limit=1024,
                posterior_samples=16,
                stop_after_epochs=20,
                max_num_epochs=100,
                seed=2002,
                extra_args=(
                    "--train-baseline-drift-std",
                    "0.10",
                    "--eval-baseline-drift-std",
                    "0.10",
                    "--hidden-features",
                    "192",
                    "--num-transforms",
                    "8",
                ),
            ),
            BatchStep(
                step_id="snpe_mask20",
                kind="sbi",
                description="SNPE-MAF smoke with matched masking retraining and masking evaluation",
                params_file="src/pytorch/configs/hh/params_sbi_hh_campaign.yaml",
                sbi_method="snpe",
                density_estimator="maf",
                feature_mode="raw_plus_fft256_summary12",
                pass_curr=True,
                n_train=12288,
                eval_limit=1024,
                posterior_samples=16,
                stop_after_epochs=20,
                max_num_epochs=100,
                seed=2002,
                extra_args=(
                    "--train-mask-fraction",
                    "0.20",
                    "--eval-mask-fraction",
                    "0.20",
                    "--hidden-features",
                    "192",
                    "--num-transforms",
                    "8",
                ),
            ),
        ),
    ),
    BatchDefinition(
        batch_id="sci06_public_extensions",
        sequence=160,
        title="Scientific smoke: public extension coverage",
        suite="scientific_smoke",
        scientific_role="coverage_expansion",
        summary="Falcon-sized public extension reproduction that exercises the lighter posterior and decision-rule surface, while leaving the heavier native-framework and surrogate branches to the complete canonical suite.",
        requires_hh_tar=True,
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=4,
        preferred_gpu="A30",
        depends_on=("sci05_robustness",),
        notes=(
            "This batch keeps the lighter extension surface in the scientific suite. The complete canonical suite adds the heavier BayesFlow, Swyft, and assumption-conditioned surrogate branches.",
        ),
        steps=(
            BatchStep(
                step_id="fmpe_extension",
                kind="sbi",
                description="FMPE extension smoke on enriched features",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                sbi_method="fmpe",
                density_estimator="maf",
                feature_mode="raw_plus_fft256_summary12",
                pass_curr=True,
                n_train=4096,
                eval_limit=128,
                posterior_samples=16,
                stop_after_epochs=20,
                max_num_epochs=100,
                seed=20260425,
                extra_args=("--num-transforms", "6"),
            ),
            BatchStep(
                step_id="npse_extension",
                kind="sbi",
                description="NPSE extension smoke on enriched features",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                sbi_method="npse",
                density_estimator="maf",
                feature_mode="raw_plus_fft256_summary12",
                pass_curr=True,
                n_train=4096,
                eval_limit=128,
                posterior_samples=16,
                stop_after_epochs=20,
                max_num_epochs=100,
                seed=20260425,
                extra_args=("--device", "cpu", "--num-transforms", "6"),
            ),
            BatchStep(
                step_id="snpe_validate_calibrated",
                kind="sbi",
                description="SNPE smoke with validation-calibrated decision-rule selection",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                sbi_method="snpe",
                density_estimator="maf",
                feature_mode="raw_plus_fft256_summary12",
                pass_curr=True,
                n_train=4096,
                eval_limit=128,
                posterior_samples=16,
                stop_after_epochs=20,
                max_num_epochs=100,
                seed=20260425,
                extra_args=(
                    "--decision-rule",
                    "validate_calibrated",
                    "--selection-candidate-rules",
                    "mean,median",
                    "--num-transforms",
                    "6",
                ),
            ),
        ),
    ),
    BatchDefinition(
        batch_id="sci07_execution_path",
        sequence=170,
        title="Scientific smoke: execution-path optimizations",
        suite="scientific_smoke",
        scientific_role="engineering_support",
        summary="Falcon-sized HH cache-path reproduction, so the public execution-path optimizations can be exercised through the distributed launcher with cache-enabled public settings.",
        requires_hh_tar=True,
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=4,
        preferred_gpu="A30",
        depends_on=("sci02_execution_policy",),
        steps=(
            BatchStep(
                step_id="cache_copy_to_node_train",
                kind="interactive_dnn",
                description="Cache-enabled HH smoke train with node-local tar extraction",
                params_file="src/pytorch/configs/hh/params_dnn_tar_hh_cache_campaign.yaml",
                pass_curr=True,
                save_predictions="none",
                split_eval_after_train=True,
                skip_inline_split_eval=True,
                step_nnodes=1,
                nproc_per_node=1,
                env_overrides=(("DATA_ACCESS_MODE", "copy_to_node"),),
            ),
            BatchStep(
                step_id="cache_copy_to_node_eval",
                kind="interactive_dnn",
                description="Cache-enabled HH smoke eval with node-local tar extraction",
                params_file="src/pytorch/configs/hh/params_dnn_tar_hh_cache_campaign.yaml",
                pass_curr=True,
                save_predictions="none",
                load_from_step="cache_copy_to_node_train",
                step_nnodes=1,
                nproc_per_node=1,
                env_overrides=(("DATA_ACCESS_MODE", "copy_to_node"),),
            ),
            BatchStep(
                step_id="cache_tar_in_place_train",
                kind="interactive_dnn",
                description="Cache-enabled HH smoke train with tar-in-place access",
                params_file="src/pytorch/configs/hh/params_dnn_tar_hh_cache_campaign.yaml",
                pass_curr=True,
                save_predictions="none",
                split_eval_after_train=True,
                skip_inline_split_eval=True,
                step_nnodes=1,
                nproc_per_node=1,
                env_overrides=(("DATA_ACCESS_MODE", "tar_in_place"),),
            ),
            BatchStep(
                step_id="cache_tar_in_place_eval",
                kind="interactive_dnn",
                description="Cache-enabled HH smoke eval with tar-in-place access",
                params_file="src/pytorch/configs/hh/params_dnn_tar_hh_cache_campaign.yaml",
                pass_curr=True,
                save_predictions="none",
                load_from_step="cache_tar_in_place_train",
                step_nnodes=1,
                nproc_per_node=1,
                env_overrides=(("DATA_ACCESS_MODE", "tar_in_place"),),
            ),
        ),
    ),
    BatchDefinition(
        batch_id="can08_aligned_frameworks",
        sequence=180,
        title="Canonical complete: aligned framework branches",
        suite="canonical_complete",
        scientific_role="coverage_expansion",
        summary="Runs the previously missing BayesFlow and Swyft aligned-framework branches against the public HH contract, so the native framework comparison surface is part of the repository rather than remaining private workspace state.",
        requires_hh_tar=True,
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=4,
        preferred_gpu="A30",
        depends_on=("sci04_posterior_followup",),
        steps=(
            BatchStep(
                step_id="bayesflow_concat",
                kind="script",
                description="BayesFlow aligned concat baseline",
                script_path="scripts/run_hh_track4_aligned_multicurrent_bayesflow_20260425.py",
                python_bin_override=".venv-bayesflow/bin/python",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                extra_args=("--aggregation", "concat", "--feature-mode", "raw_plus_fft256_summary12"),
            ),
            BatchStep(
                step_id="bayesflow_meanstd",
                kind="script",
                description="BayesFlow aligned meanstd baseline",
                script_path="scripts/run_hh_track4_aligned_multicurrent_bayesflow_20260425.py",
                python_bin_override=".venv-bayesflow/bin/python",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                extra_args=("--aggregation", "meanstd", "--feature-mode", "raw_plus_fft256_summary12"),
            ),
            BatchStep(
                step_id="bayesflow_structured",
                kind="script",
                description="BayesFlow structured aligned baseline",
                script_path="scripts/run_hh_track4_aligned_multicurrent_bayesflow_structured_20260425.py",
                python_bin_override=".venv-bayesflow/bin/python",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                extra_args=("--feature-mode", "raw_plus_fft256_summary12"),
            ),
            BatchStep(
                step_id="bayesflow_set",
                kind="script",
                description="BayesFlow set-transformer posterior branch",
                script_path="scripts/run_hh_track4_aligned_multicurrent_bayesflow_set_20260426.py",
                python_bin_override=".venv-bayesflow/bin/python",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                extra_args=("--feature-mode", "raw_plus_fft256_summary12", "--summary-network", "set_transformer"),
            ),
            BatchStep(
                step_id="bayesflow_temporal",
                kind="script",
                description="BayesFlow temporal posterior branch",
                script_path="scripts/run_hh_track4_aligned_multicurrent_bayesflow_temporal_20260426.py",
                python_bin_override=".venv-bayesflow/bin/python",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                extra_args=("--summary-network", "time_series_transformer"),
            ),
            BatchStep(
                step_id="swyft_concat",
                kind="script",
                description="Swyft concat aligned baseline",
                script_path="scripts/run_hh_track4_aligned_multicurrent_swyft_20260425.py",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                extra_args=("--aggregation", "concat"),
            ),
            BatchStep(
                step_id="swyft_meanstd",
                kind="script",
                description="Swyft meanstd aligned baseline",
                script_path="scripts/run_hh_track4_aligned_multicurrent_swyft_20260425.py",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                extra_args=("--aggregation", "meanstd"),
            ),
            BatchStep(
                step_id="swyft_structured",
                kind="script",
                description="Swyft structured aligned baseline",
                script_path="scripts/run_hh_track4_aligned_multicurrent_swyft_structured_20260425.py",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                extra_args=("--aggregation", "meanstd"),
            ),
            BatchStep(
                step_id="swyft_tmnre",
                kind="script",
                description="Swyft TMNRE follow-up branch",
                script_path="scripts/run_hh_track4_aligned_multicurrent_swyft_tmnre_20260425.py",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                load_from_step="swyft_meanstd",
                extra_args=("--stage1-run-dir", "{LOAD_FROM_STEP_ROOT}"),
            ),
            BatchStep(
                step_id="swyft_tmnre_score_prune",
                kind="script",
                description="Swyft TMNRE score-prune follow-up branch",
                script_path="scripts/run_hh_track4_aligned_multicurrent_swyft_tmnre_score_prune_20260426.py",
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                pass_data_dir=True,
                load_from_step="swyft_meanstd",
                extra_args=("--stage1-run-dir", "{LOAD_FROM_STEP_ROOT}"),
            ),
        ),
    ),
    BatchDefinition(
        batch_id="can09_posterior_decision_rules",
        sequence=190,
        title="Canonical complete: posterior decision-rule analysis",
        suite="canonical_complete",
        scientific_role="coverage_expansion",
        summary="Analyzes the BayesFlow, Swyft, and public SBI posterior outputs into explicit decision-rule rows, so the posterior rule surface is regenerated from the repository outputs.",
        requires_hh_tar=True,
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=4,
        preferred_gpu="A30",
        depends_on=("can08_aligned_frameworks", "sci06_public_extensions"),
        steps=(
            BatchStep(
                step_id="decision_rule_analysis",
                kind="script",
                description="Posterior decision-rule analysis across framework and SBI outputs",
                script_path="scripts/analyze_hh_track4_posterior_decision_rules_20260425.py",
                pass_data_dir=True,
                params_file="src/pytorch/configs/hh/params_sbi_hh_followup.yaml",
                extra_args=(
                    "--run-roots",
                    "{BATCH_ROOT}/../can08_aligned_frameworks,{RUN_ROOT}/sci04_posterior_followup,{RUN_ROOT}/sci06_public_extensions",
                ),
            ),
        ),
    ),
    BatchDefinition(
        batch_id="can10_assumption_conditioned_surrogates",
        sequence=200,
        title="Canonical complete: assumption-conditioned surrogate branches",
        suite="canonical_complete",
        scientific_role="coverage_expansion",
        summary="Runs the previously missing compact-HH surrogate branches, namely sandbox, fit search, hybrid refinement, Wasserstein ABC, active-sequential design, and ASNPE-style follow-up.",
        requires_hh_tar=True,
        requires_slurm=True,
        cluster_label="Falcon",
        min_nodes=4,
        preferred_gpu="A30",
        depends_on=("sci06_public_extensions",),
        steps=(
            BatchStep(
                step_id="compact_hh_sandbox",
                kind="script",
                description="Compact-HH sandbox against observed HH traces",
                script_path="scripts/run_hh_track4_assumption_conditioned_compact_hh_sandbox_20260424.py",
                pass_data_dir=True,
            ),
            BatchStep(
                step_id="compact_hh_fit_search",
                kind="script",
                description="Compact-HH direct-fitting search branch",
                script_path="scripts/run_hh_track4_assumption_conditioned_compact_hh_fit_search_20260424.py",
                pass_data_dir=True,
            ),
            BatchStep(
                step_id="hybrid_refinement_midpoint",
                kind="script",
                description="Hybrid local refinement branch seeded from the prior midpoint",
                script_path="scripts/run_hh_track4_assumption_conditioned_hybrid_refinement_20260425.py",
                pass_data_dir=True,
                extra_args=("--init-mode", "midpoint"),
            ),
            BatchStep(
                step_id="wasserstein_abc",
                kind="script",
                description="Sliced-Wasserstein ABC surrogate branch",
                script_path="scripts/run_hh_track4_assumption_conditioned_wasserstein_abc_20260425.py",
                pass_data_dir=True,
            ),
            BatchStep(
                step_id="active_sequential_policy_suite",
                kind="script",
                description="Active-sequential policy comparison branch",
                script_path="scripts/run_hh_track4_assumption_conditioned_active_sequential_policy_suite_20260425.py",
            ),
            BatchStep(
                step_id="asnpe_surrogate",
                kind="script",
                description="ASNPE-style surrogate branch",
                script_path="scripts/run_hh_track4_assumption_conditioned_asnpe_20260426.py",
            ),
        ),
    ),
)


SUITES: Dict[str, Tuple[str, ...]] = {
    "falcon_a30_smoke": (
        "smk01_fhn_baseline",
        "smk02_hh_dnn",
        "smk03_hh_classical",
        "smk04_hh_sbi",
    ),
    "canonical_complete_smoke": (
        "smk01_fhn_baseline",
        "smk02_hh_dnn",
        "smk03_hh_classical",
        "smk04_hh_sbi",
        "smk05_bayesflow_frameworks",
        "smk06_swyft_frameworks",
        "smk07_posterior_decision_rules",
        "smk08_assumption_conditioned_surrogates",
    ),
    "canonical_falcon": (
        "fal01_hh_4node_a30_dnn",
        "fal02_hh_classical_reference",
        "fal03_hh_sbi_reference",
    ),
    "scientific_smoke": (
        "sci01_benchmark_parity",
        "sci02_execution_policy",
        "sci03_direct_frontier",
        "sci04_posterior_followup",
        "sci05_robustness",
        "sci06_public_extensions",
        "sci07_execution_path",
    ),
    "canonical_complete": (
        "sci01_benchmark_parity",
        "sci02_execution_policy",
        "sci03_direct_frontier",
        "sci04_posterior_followup",
        "sci05_robustness",
        "sci06_public_extensions",
        "can08_aligned_frameworks",
        "can09_posterior_decision_rules",
        "can10_assumption_conditioned_surrogates",
        "sci07_execution_path",
    ),
}


BATCH_BY_ID: Dict[str, BatchDefinition] = {batch.batch_id: batch for batch in BATCHES}
ORDERED_BATCH_IDS: Tuple[str, ...] = tuple(batch.batch_id for batch in sorted(BATCHES, key=lambda item: item.sequence))


def get_batch(batch_id: str) -> BatchDefinition:
    return BATCH_BY_ID[batch_id]


def list_batches() -> Tuple[BatchDefinition, ...]:
    return tuple(sorted(BATCHES, key=lambda item: item.sequence))


def batches_for_suite(suite: str) -> Tuple[BatchDefinition, ...]:
    batch_ids = SUITES[suite]
    return tuple(get_batch(batch_id) for batch_id in batch_ids)


def batches_through(batch_id: str) -> Tuple[BatchDefinition, ...]:
    target = get_batch(batch_id)
    return tuple(batch for batch in list_batches() if batch.sequence <= target.sequence)


def batch_to_dict(batch: BatchDefinition) -> Dict[str, object]:
    out = asdict(batch)
    out["steps"] = [asdict(step) for step in batch.steps]
    return out


def suite_names() -> Tuple[str, ...]:
    return tuple(sorted(SUITES.keys()))


def iter_dependency_chain(batch: BatchDefinition) -> Iterable[str]:
    for dep in batch.depends_on:
        yield dep
